version: '3.3'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    env_file:
      - docker.env
    ports:
      - '15432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
  postgres:
    driver: bridge

volumes:
  db:
    driver: local
