"""empty message

Revision ID: 64d19ac3281a
Revises: 6dd83ad0d2dc
Create Date: 2022-07-16 19:40:48.251840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64d19ac3281a'
down_revision = '6dd83ad0d2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('time', sa.DateTime(), nullable=False))
    op.drop_column('activity', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('activity', 'time')
    # ### end Alembic commands ###
