"""empty message

Revision ID: b3037f814f3a
Revises: f571a532149c
Create Date: 2022-07-16 17:35:30.223020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3037f814f3a'
down_revision = 'f571a532149c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('is_checkin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_checkin')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
