"""empty message

Revision ID: f571a532149c
Revises: 093dac49d5c4
Create Date: 2022-07-16 17:30:45.436008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f571a532149c'
down_revision = '093dac49d5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('type', sa.Enum('CHECK_IN', 'CHECK_OUT', name='attendancetype'), nullable=False))
    op.drop_column('attendance', 'attendance_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('attendance_type', postgresql.ENUM('CHECK_IN', 'CHECK_OUT', name='attendancetype'), autoincrement=False, nullable=False))
    op.drop_column('attendance', 'type')
    # ### end Alembic commands ###
